db_name: FIXME
db_user: FIXME
db_pass: FIXME
db_dial: FIXME
db_host: FIXME
db_port: FIXME
db_sid:  FIXME

gituser: FIXME
gitpass: FIXME

supervisor_inet_port: FIXME
supervisor_inet_username: FIXME
supervisor_inet_password: FIXME
